<?php echo $this->getContent() ?>
<p> Form for add address <p>
<form action="/user/<?php echo $userID ?>" method="post">
	<p>
		<label>
			City
		</label>
		<?php echo $form->render('city'); ?>
	</p>

	<p>
		<label>
			Postcode
		</label>
		<?php echo $form->render('postcode'); ?>
	</p>
	
	<p>
		<label>
			Region
		</label>
		<?php echo $form->render('region'); ?>
	</p>
	
	<p>
		<label>
			Street
		</label>
		<?php echo $form->render('street'); ?>
	</p>
	<p>
		<input type="submit" value="send">
	</p>


</form>
